[build]
	command = "npm run serverLaunch"
	functions = "../netlify/functions"
	publish = "public"

[functions]
    node_bundler = "esbuild"
	directory = "/netlify/functions"

[dev]
	command = "npm run server"
	targetPort = 8080
	publish = "public"
	framework = "eleventy"